language: node_js
sudo: false
env:
  global:
  - DEBUG='base:app:request,auth:*,server,test:*'
  - CXX=g++-4.8
node_js:
- '6'
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: npm test
